### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by highwaterr** [askmike/deribit-v2-ws#15]
hi there, im running into an error when trying to run this.

/Desktop/deribit-v2-ws/connection.js:35
  handleError = (e) => {
              ^

SyntaxError: Unexpected token =
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

thanks

**Comment by p0nt** [comment]
Upgrade your node to a newer version and it will work.

**Comment by highwaterr** [comment]
Thanks!
