### ISSUE TITLE
unhandeled exceptions

### ISSUE THREAD

**Issue by DOABrownie** [askmike/deribit-v2-ws#16]
Hi all. i keep getting the following crash when using this repo (it happened now and then.. 2-3 times a day). i need it to be running 24/7.. not sure what to do

2020-04-29T11:02:17.507Z [DERIBIT] NO PING RESPONSE
2020-04-29T11:02:17.507Z [DERIBIT] TERMINATED WS CON
2020-04-29T11:02:17.510Z [DERIBIT] CLOSED CON
when FAILED: Error: Deribit connection closed.
CANCEL ORDERS - deribit
{
  "which": "tagged",
  "tag": "SL"
}
(node:5408) UnhandledPromiseRejectionWarning: Error: Deribit connection closed.
    at /home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/connection.js:62:42
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onclose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/connection.js:61:28)
    at WebSocket.onClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:321:20)
    at WebSocket.emitClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:333:22)
    at net.js:668:12
    at TCP.done (_tls_wrap.js:558:7)
(node:5408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not hand
led with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection i
d: 1)
(node:5408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-04-29T11:02:18.011Z [DERIBIT] RECONNECTING...
Calculated order size as Zero.
tsl FAILED: Error: No funds available or order size is 0
de-referencing exchange deribit
Deribit exchange closing down
2020-04-29T11:39:14.697Z [DERIBIT] NO PING RESPONSE
2020-04-29T11:39:14.697Z [DERIBIT] TERMINATED WS CON
2020-04-29T11:39:14.698Z [DERIBIT] CLOSED CON
(node:5408) UnhandledPromiseRejectionWarning: Error: Deribit connection closed.
    at /home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/connection.js:62:42
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onclose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/connection.js:61:28)
    at WebSocket.onClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:321:20)
    at WebSocket.emitClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:333:22)
    at net.js:668:12
    at TCP.done (_tls_wrap.js:558:7)
(node:5408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not hand
led with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection i
d: 2)
2020-04-29T11:39:15.199Z [DERIBIT] RECONNECTING...
2020-04-29T12:40:38.950Z [DERIBIT] CLOSED CON
2020-04-29T12:40:39.451Z [DERIBIT] RECONNECTING...
2020-04-29T12:53:08.134Z [DERIBIT] CLOSED CON
2020-04-29T12:53:08.635Z [DERIBIT] RECONNECTING...
2020-04-29T12:53:52.910Z [DERIBIT] CLOSED CON
2020-04-29T12:53:53.411Z [DERIBIT] RECONNECTING...
2020-04-29T12:56:24.311Z [DERIBIT] NO PING RESPONSE
2020-04-29T12:56:24.312Z [DERIBIT] TERMINATED WS CON
2020-04-29T12:56:24.312Z [DERIBIT] CLOSED CON
(node:5408) UnhandledPromiseRejectionWarning: Error: Deribit connection closed.
    at /home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/connection.js:62:42
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onclose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/connection.js:61:28)
    at WebSocket.onClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:321:20)
    at WebSocket.emitClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:333:22)
    at net.js:668:12
    at TCP.done (_tls_wrap.js:558:7)
(node:5408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2020-04-29T12:56:24.813Z [DERIBIT] RECONNECTING...
2020-04-29T12:57:55.702Z [DERIBIT] NO PING RESPONSE
2020-04-29T12:57:55.702Z [DERIBIT] TERMINATED WS CON
2020-04-29T12:57:55.703Z [DERIBIT] CLOSED CON
(node:5408) UnhandledPromiseRejectionWarning: Error: Deribit connection closed.
    at /home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/connection.js:62:42
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onclose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/connection.js:61:28)
    at WebSocket.onClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:321:20)
    at WebSocket.emitClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/websocket.js:191:10)
    at TLSSocket.socketOnClose (/home/btc_magnet_dl/BTC_Magnet/node_modules/deribit-v2-ws/node_modules/ws/lib/websocket.js:850:15)
    at TLSSocket.emit (events.js:333:22)
    at net.js:668:12
    at TCP.done (_tls_wrap.js:558:7)
(node:5408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
2020-04-29T12:57:56.204Z [DERIBIT] RECONNECTING...
2020-04-29T13:02:22.871Z [DERIBIT] CLOSED CON
2020-04-29T13:02:23.372Z [DERIBIT] RECONNECTING...

**Comment by askmike** [comment]
You're trying to cancel orders when the connection is closed. This lib does API calls over the websocket, which you cannot do when it is closed.

In your specific situation (want to cancel orders when the websocket closes) I would remove your cancel order code and toggle the cancel on disconnect in the API key settings on Deribit.

**Comment by askmike** [comment]
Alternatively, you can send a cancel order API call via the REST API, this works when the WS goes down BUT you still have internet (and Deribit is up) - if you don't have internet or Deribit is down there is obviously no way to cancel orders. This lib is only for connecting to the websocket so would have to code that yourself.

**Comment by DOABrownie** [comment]
O Ok. i thought this opened an upgrade to WS on initial connection and then the WS remained open... EG im sending many many orders through / minute (Market Maker function) and i dont want to open a WS for each order set... any way to hold the WS open..

**Comment by askmike** [comment]
> i thought this opened an upgrade to WS on initial connection and then the WS remained open... 

That's the plan yes, but sometimes things go wrong. Your logs say:

> [DERIBIT] NO PING RESPONSE

Meaning my lib thinks the WS isn't actually open anymore because it can't receive ping data.

Are you running this form a home PC? Far away from London (where Deribit's servers are hosted)? Seems like you have network connectivity issues.

**Comment by askmike** [comment]
closing this, as I think you're problems are network related. Feel free elaborate further.

**Comment by DOABrownie** [comment]
O OK sorry. i thought your Lib was intending to 'Reconnect' via your re connection function.
i would highly doubt it is network related. My server is Fiber Direct and i am running many instances and the other instances dont drop out when one of them does.. (all the instances are running on the same server (public IP)..
also i console logged whether your code was holding my API key correctly during reconnect and it is.. im not trying to troll im just really trying to ensure 100% connectivity for my instances and if i do loose connection or other interruptions i wish for it to keep trying to and eventually reconnecting.

Thanking you in advance AskMike i really appreciate your time and input here

**Comment by askmike** [comment]
> O OK sorry. i thought your Lib was intending to 'Reconnect' via your re connection function.

Yep it does! But that can take a few seconds. Meanwhile you can't send messages. You can see that here:

    2020-04-29T12:53:08.134Z [DERIBIT] CLOSED CON
    2020-04-29T12:53:08.635Z [DERIBIT] RECONNECTING...
    2020-04-29T12:53:52.910Z [DERIBIT] CLOSED CON
    2020-04-29T12:53:53.411Z [DERIBIT] RECONNECTING...

> im not trying to troll im just really trying to ensure 100% connectivity for my instances and if i do loose connection or other interruptions i wish for it to keep trying to and eventually reconnecting.

The lib detects that sometimes the connection breaks, it will retry when this happens but can take some time. The specific error you are seeing: `Deribit connection closed.` comes from messages you tried to send but failed because of WS disconnects. It's just fatal and crashes your app because you are not handling the error. You can wrap the `request` function you are calling from my lib in a try/catch statement (or `.catch` method if you are using futures), and you can handle accordingly. If you create an order and the WS disonnects in the middle of your request my lib doesn't know whether this happened or not, so you need to handle these errors yourself.
