### ISSUE TITLE
stuck on "[DERIBIT] RECONNECTING..."

### ISSUE THREAD

**Issue by nswbmw** [askmike/deribit-v2-ws#22]
I don't know if it's the test environment problem, throw error with `getaddrinfo EAI_AGAIN test.deribit.com`, after a few tries, it finilly stuck on "[DERIBIT] RECONNECTING..."
**BTW**: I start 2 deribit ws client

```
2021-10-25T00:57:37.138Z [DERIBIT] NO PING RESPONSE
2021-10-25T00:57:37.143Z [DERIBIT] TERMINATED WS CON
2021-10-25T00:57:37.146Z [DERIBIT] NO PING RESPONSE
2021-10-25T00:57:37.147Z [DERIBIT] TERMINATED WS CON
2021-10-25T00:57:37.151Z [DERIBIT] CLOSED CON
2021-10-25T00:57:37.168Z [DERIBIT] CLOSED CON
2021-10-25T00:57:37.652Z [DERIBIT] RECONNECTING...
2021-10-25T00:57:37.674Z [DERIBIT] RECONNECTING...
2021-10-25T00:57:57.687Z [DERIBIT] DERI ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      message: [Function],
      open: [Function],
      error: [Array],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://test.deribit.com/ws/api/v2',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'getaddrinfo EAI_AGAIN test.deribit.com',
  error: Error: getaddrinfo EAI_AGAIN test.deribit.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'test.deribit.com'
  }
}
2021-10-25T00:57:57.691Z [DERIBIT] DERI ERROR Error: getaddrinfo EAI_AGAIN test.deribit.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'test.deribit.com'
}
2021-10-25T00:57:57.692Z [DERIBIT] CLOSED CON
2021-10-25T00:57:57.694Z [DERIBIT] DERI ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      message: [Function],
      open: [Function],
      error: [Array],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://test.deribit.com/ws/api/v2',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'getaddrinfo EAI_AGAIN test.deribit.com',
  error: Error: getaddrinfo EAI_AGAIN test.deribit.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'test.deribit.com'
  }
}
2021-10-25T00:57:57.695Z [DERIBIT] DERI ERROR Error: getaddrinfo EAI_AGAIN test.deribit.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'test.deribit.com'
}
2021-10-25T00:57:57.696Z [DERIBIT] CLOSED CON
2021-10-25T00:57:58.194Z [DERIBIT] RECONNECTING...
2021-10-25T00:57:58.197Z [DERIBIT] RECONNECTING...
2021-10-25T00:58:18.212Z [DERIBIT] DERI ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      message: [Function],
      open: [Function],
      error: [Array],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://test.deribit.com/ws/api/v2',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'getaddrinfo EAI_AGAIN test.deribit.com',
  error: Error: getaddrinfo EAI_AGAIN test.deribit.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'test.deribit.com'
  }
}
2021-10-25T00:58:18.214Z [DERIBIT] DERI ERROR Error: getaddrinfo EAI_AGAIN test.deribit.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'test.deribit.com'
}
2021-10-25T00:58:18.215Z [DERIBIT] CLOSED CON
2021-10-25T00:58:18.216Z [DERIBIT] DERI ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      message: [Function],
      open: [Function],
      error: [Array],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://test.deribit.com/ws/api/v2',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'getaddrinfo EAI_AGAIN test.deribit.com',
  error: Error: getaddrinfo EAI_AGAIN test.deribit.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'test.deribit.com'
  }
}
2021-10-25T00:58:18.217Z [DERIBIT] DERI ERROR Error: getaddrinfo EAI_AGAIN test.deribit.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'test.deribit.com'
}
2021-10-25T00:58:18.218Z [DERIBIT] CLOSED CON
2021-10-25T00:58:18.716Z [DERIBIT] RECONNECTING...
2021-10-25T00:58:18.719Z [DERIBIT] RECONNECTING...
2021-10-25T00:58:38.737Z [DERIBIT] DERI ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      message: [Function],
      open: [Function],
      error: [Array],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://test.deribit.com/ws/api/v2',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'getaddrinfo EAI_AGAIN test.deribit.com',
  error: Error: getaddrinfo EAI_AGAIN test.deribit.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'test.deribit.com'
  }
}
2021-10-25T00:58:38.739Z [DERIBIT] DERI ERROR Error: getaddrinfo EAI_AGAIN test.deribit.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'test.deribit.com'
}
2021-10-25T00:58:38.740Z [DERIBIT] CLOSED CON
2021-10-25T00:58:38.741Z [DERIBIT] DERI ERROR ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      message: [Function],
      open: [Function],
      error: [Array],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://test.deribit.com/ws/api/v2',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'getaddrinfo EAI_AGAIN test.deribit.com',
  error: Error: getaddrinfo EAI_AGAIN test.deribit.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: 'test.deribit.com'
  }
}
2021-10-25T00:58:38.742Z [DERIBIT] DERI ERROR Error: getaddrinfo EAI_AGAIN test.deribit.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'test.deribit.com'
}
2021-10-25T00:58:38.742Z [DERIBIT] CLOSED CON
2021-10-25T00:58:39.240Z [DERIBIT] RECONNECTING...
2021-10-25T00:58:39.243Z [DERIBIT] RECONNECTING...
```

**Comment by askmike** [comment]
These are DNS lookup errors: whatever DNS server you are using is unable to find test.deribit.com. This is a networking problem on your side. You can try using 1.1.1.1 or 8.8.8.8 as your dns server and see if that fixes it.
